In [9]:
import pandas as pd 
import yfinance as yf 
import datetime 
from datetime import date, timedelta 
import plotly.graph_objects as go 
import plotly.express as px

In [ ]:
today = date.today()

d1 = today.strftime("%Y-%m-%d")
end_date = d1
d2 = date.today() - timedelta(days=360)
d2 = d2.strftime("%Y-%m-%d")
start_date = d2

df = yf.download(['AAPL', 'MSFT', 'GOOG','AMZN','FB'],
                      start=start_date, 
                      end=end_date, 
                      progress=False)
print(df.head())

C:\Users\Abdelruhman Elfekky\AppData\Local\Temp\ipykernel_7636\2110894163.py:13: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(['AAPL', 'MSFT', 'GOOG','AMZN','FB'],

Price            Close                                                High  \
Ticker            AAPL        AMZN  FB        GOOG        MSFT        AAPL
Date
2024-11-22  228.835022  197.119995 NaN  165.844177  414.721161  229.681201
2024-11-25  231.821533  201.449997 NaN  168.691681  416.501373  232.199827
2024-11-26  234.001663  207.860001 NaN  169.876511  425.651093  234.509377
2024-11-27  233.872238  205.740005 NaN  170.075638  420.678436  234.628826
2024-11-29  236.261444  207.889999 NaN  169.747070  421.145844  236.739279

Price                                               ...        Open  \
Ticker            AMZN  FB        GOOG        MSFT  ...        AAPL
Date                                                ...
2024-11-22  199.259995 NaN  167.531783  415.118969  ...  227.033174
2024-11-25  201.949997 NaN  169.717207  418.778837  ...  230.417893
2024-11-26  208.000000 NaN  170.747698  426.695373  ...  232.279457
2024-11-27  207.639999 NaN  170.394235  424.895286  ...  233.414318
2024-11-29  208.199997 NaN  170.125404  422.558097  ...  233.752786

Price                                                 Volume                \
Ticker            AMZN  FB        GOOG        MSFT      AAPL      AMZN  FB
Date
2024-11-22  198.250000 NaN  166.431603  409.121923  38168300  31530800 NaN
2024-11-25  199.279999 NaN  167.257969  416.093610  90152800  40685700 NaN
2024-11-26  201.899994 NaN  168.751445  417.297003  45986200  41673700 NaN
2024-11-27  206.979996 NaN  169.936233  422.786846  33498400  28061600 NaN
2024-11-29  205.830002 NaN  169.318936  417.794265  28481400  24892400 NaN

Price
Ticker          GOOG      MSFT
Date
2024-11-22  24497000  24814600
2024-11-25  21395700  27691100
2024-11-26  14937500  23458900
2024-11-27  12433400  18332400
2024-11-29   9250700  16271900

[5 rows x 25 columns]

In [2]:
# Most likely the ticker FB is returning NaNs because Facebook changed its ticker to META (Meta Platforms, Inc.)
# in 2022 — yfinance might return NaNs for FB today.
df.isna().sum()

Price   Ticker
Close   AAPL        0
        AMZN        0
        FB        145
        GOOG        0
        MSFT        0
High    AAPL        0
        AMZN        0
        FB        145
        GOOG        0
        MSFT        0
Low     AAPL        0
        AMZN        0
        FB        145
        GOOG        0
        MSFT        0
Open    AAPL        0
        AMZN        0
        FB        145
        GOOG        0
        MSFT        0
Volume  AAPL        0
        AMZN        0
        FB        145
        GOOG        0
        MSFT        0
dtype: int64

In [3]:
tickers = ['AAPL','MSFT','GOOG','AMZN','META']  # replace FB with META
df = yf.download(tickers, start=start_date, end=end_date, progress=False)

C:\Users\Abdelruhman Elfekky\AppData\Local\Temp\ipykernel_7636\326070628.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(tickers, start=start_date, end=end_date, progress=False)

In [4]:
print(df.head())

Price            Close                                                  \
Ticker            AAPL        AMZN        GOOG        META        MSFT
Date
2024-11-22  228.835022  197.119995  165.844177  557.387390  414.721161
2024-11-25  231.821533  201.449997  168.691681  563.338684  416.501373
2024-11-26  234.001663  207.860001  169.876511  571.742249  425.651093
2024-11-27  233.872238  205.740005  170.075638  567.415833  420.678436
2024-11-29  236.261444  207.889999  169.747070  572.519836  421.145844

Price             High                                                  ...  \
Ticker            AAPL        AMZN        GOOG        META        MSFT  ...
Date                                                                    ...
2024-11-22  229.681201  199.259995  167.531783  562.062692  415.118969  ...
2024-11-25  232.199827  201.949997  169.717207  570.795280  418.778837  ...
2024-11-26  234.509377  208.000000  170.747698  575.689858  426.695373  ...
2024-11-27  234.628826  207.639999  170.394235  573.177683  424.895286  ...
2024-11-29  236.739279  208.199997  170.125404  576.646874  422.558097  ...

Price             Open                                                  \
Ticker            AAPL        AMZN        GOOG        META        MSFT
Date
2024-11-22  227.033174  198.250000  166.431603  561.783540  409.121923
2024-11-25  230.417893  199.279999  167.257969  560.338109  416.093610
2024-11-26  232.279457  201.899994  168.751445  564.225904  417.297003
2024-11-27  233.414318  206.979996  169.936233  573.087999  422.786846
2024-11-29  233.752786  205.830002  169.318936  567.216504  417.794265

Price         Volume
Ticker          AAPL      AMZN      GOOG      META      MSFT
Date
2024-11-22  38168300  31530800  24497000   9164000  24814600
2024-11-25  90152800  40685700  21395700  13599800  27691100
2024-11-26  45986200  41673700  14937500  10356600  23458900
2024-11-27  33498400  28061600  12433400   7200200  18332400
2024-11-29  28481400  24892400   9250700   7130500  16271900

[5 rows x 25 columns]

In [5]:
print('*** After replacing FB with META ***')
print(df.isna().sum()) # it clear now

*** After replacing FB with META ***
Price   Ticker
Close   AAPL      0
        AMZN      0
        GOOG      0
        META      0
        MSFT      0
High    AAPL      0
        AMZN      0
        GOOG      0
        META      0
        MSFT      0
Low     AAPL      0
        AMZN      0
        GOOG      0
        META      0
        MSFT      0
Open    AAPL      0
        AMZN      0
        GOOG      0
        META      0
        MSFT      0
Volume  AAPL      0
        AMZN      0
        GOOG      0
        META      0
        MSFT      0
dtype: int64

In [6]:
df.columns

MultiIndex([( 'Close', 'AAPL'),
            ( 'Close', 'AMZN'),
            ( 'Close', 'GOOG'),
            ( 'Close', 'META'),
            ( 'Close', 'MSFT'),
            (  'High', 'AAPL'),
            (  'High', 'AMZN'),
            (  'High', 'GOOG'),
            (  'High', 'META'),
            (  'High', 'MSFT'),
            (   'Low', 'AAPL'),
            (   'Low', 'AMZN'),
            (   'Low', 'GOOG'),
            (   'Low', 'META'),
            (   'Low', 'MSFT'),
            (  'Open', 'AAPL'),
            (  'Open', 'AMZN'),
            (  'Open', 'GOOG'),
            (  'Open', 'META'),
            (  'Open', 'MSFT'),
            ('Volume', 'AAPL'),
            ('Volume', 'AMZN'),
            ('Volume', 'GOOG'),
            ('Volume', 'META'),
            ('Volume', 'MSFT')],
           names=['Price', 'Ticker'])

In [7]:
df.columns = ['_'.join(col).strip() for col in df.columns]
df.columns

Index(['Close_AAPL', 'Close_AMZN', 'Close_GOOG', 'Close_META', 'Close_MSFT',
       'High_AAPL', 'High_AMZN', 'High_GOOG', 'High_META', 'High_MSFT',
       'Low_AAPL', 'Low_AMZN', 'Low_GOOG', 'Low_META', 'Low_MSFT', 'Open_AAPL',
       'Open_AMZN', 'Open_GOOG', 'Open_META', 'Open_MSFT', 'Volume_AAPL',
       'Volume_AMZN', 'Volume_GOOG', 'Volume_META', 'Volume_MSFT'],
      dtype='object')

In [8]:
df.head()

,Close_AAPL,Close_AMZN,Close_GOOG,Close_META,Close_MSFT,High_AAPL,High_AMZN,High_GOOG,High_META,High_MSFT,...,Open_AAPL,Open_AMZN,Open_GOOG,Open_META,Open_MSFT,Volume_AAPL,Volume_AMZN,Volume_GOOG,Volume_META,Volume_MSFT
Date,,,,,,,,,,,,,,,,,,,,,
2024-11-22,228.835022,197.119995,165.844177,557.387390,414.721161,229.681201,199.259995,167.531783,562.062692,415.118969,...,227.033174,198.250000,166.431603,561.783540,409.121923,38168300,31530800,24497000,9164000,24814600
2024-11-25,231.821533,201.449997,168.691681,563.338684,416.501373,232.199827,201.949997,169.717207,570.795280,418.778837,...,230.417893,199.279999,167.257969,560.338109,416.093610,90152800,40685700,21395700,13599800,27691100
2024-11-26,234.001663,207.860001,169.876511,571.742249,425.651093,234.509377,208.000000,170.747698,575.689858,426.695373,...,232.279457,201.899994,168.751445,564.225904,417.297003,45986200,41673700,14937500,10356600,23458900
2024-11-27,233.872238,205.740005,170.075638,567.415833,420.678436,234.628826,207.639999,170.394235,573.177683,424.895286,...,233.414318,206.979996,169.936233,573.087999,422.786846,33498400,28061600,12433400,7200200,18332400
2024-11-29,236.261444,207.889999,169.747070,572.519836,421.145844,236.739279,208.199997,170.125404,576.646874,422.558097,...,233.752786,205.830002,169.318936,567.216504,417.794265,28481400,24892400,9250700,7130500,16271900

In [11]:
df.columns

Index(['Close_AAPL', 'Close_AMZN', 'Close_GOOG', 'Close_META', 'Close_MSFT',
       'High_AAPL', 'High_AMZN', 'High_GOOG', 'High_META', 'High_MSFT',
       'Low_AAPL', 'Low_AMZN', 'Low_GOOG', 'Low_META', 'Low_MSFT', 'Open_AAPL',
       'Open_AMZN', 'Open_GOOG', 'Open_META', 'Open_MSFT', 'Volume_AAPL',
       'Volume_AMZN', 'Volume_GOOG', 'Volume_META', 'Volume_MSFT'],
      dtype='object')

In [17]:
df.index = pd.to_datetime(df.index)
# df = df.set_index("Date")

## show apple Candle stick

In [19]:
figure = go.Figure(data=[go.Candlestick(x = df.index, 
                    open=df["Open_AAPL"], 
                    high=df["High_AAPL"], 
                    low=df["Low_AAPL"], 
                    close=df["Close_AAPL"])]) 
figure.update_layout(title = "Apple Stock Price Analysis", 
xaxis_rangeslider_visible=False) 
figure.show()

## show Amazon Candle stick

In [20]:
figure = go.Figure(data=[go.Candlestick(x = df.index, 
                    open=df["Open_AMZN"], 
                    high=df["High_AMZN"], 
                    low=df["Low_AMZN"], 
                    close=df["Close_AMZN"])]) 
figure.update_layout(title = "Amazon Stock Price Analysis", 
xaxis_rangeslider_visible=False) 
figure.show()

## Show Google Candle stick

In [ ]:
#turn to google stock plot
figure = go.Figure(data=[go.Candlestick(x = df.index, 
                    open=df["Open_GOOG"], 
                    high=df["High_GOOG"], 
                    low=df["Low_GOOG"], 
                    close=df["Close_GOOG"])]) 
figure.update_layout(title = "Google Stock Price Analysis", 
xaxis_rangeslider_visible=False) 
figure.show()

## Show META Candle stick

In [ ]:
figure = go.Figure(data=[go.Candlestick(x = df.index, 
                    open=df["Open_META"], 
                    high=df["High_META"], 
                    low=df["Low_META"], 
                    close=df["Close_META"])]) 
figure.update_layout(title = "META Stock Price Analysis", 
xaxis_rangeslider_visible=False) 
figure.show()

In [24]:
df.columns

Index(['Close_AAPL', 'Close_AMZN', 'Close_GOOG', 'Close_META', 'Close_MSFT',
       'High_AAPL', 'High_AMZN', 'High_GOOG', 'High_META', 'High_MSFT',
       'Low_AAPL', 'Low_AMZN', 'Low_GOOG', 'Low_META', 'Low_MSFT', 'Open_AAPL',
       'Open_AMZN', 'Open_GOOG', 'Open_META', 'Open_MSFT', 'Volume_AAPL',
       'Volume_AMZN', 'Volume_GOOG', 'Volume_META', 'Volume_MSFT'],
      dtype='object')

## Show Microsoft Candle stick

In [25]:
# Show MSTF Candle stick

figure = go.Figure(data=[go.Candlestick(x = df.index, 
                    open=df["Open_MSFT"], 
                    high=df["High_MSFT"], 
                    low=df["Low_MSFT"], 
                    close=df["Close_MSFT"])]) 
figure.update_layout(title = "MSFT Stock Price Analysis", 
xaxis_rangeslider_visible=False) 
figure.show()

In [31]:
df.columns

Index(['Close_AAPL', 'Close_AMZN', 'Close_GOOG', 'Close_META', 'Close_MSFT',
       'High_AAPL', 'High_AMZN', 'High_GOOG', 'High_META', 'High_MSFT',
       'Low_AAPL', 'Low_AMZN', 'Low_GOOG', 'Low_META', 'Low_MSFT', 'Open_AAPL',
       'Open_AMZN', 'Open_GOOG', 'Open_META', 'Open_MSFT', 'Volume_AAPL',
       'Volume_AMZN', 'Volume_GOOG', 'Volume_META', 'Volume_MSFT'],
      dtype='object')

## Compare Apple vs Microsoft - normalized price, returns, correlation & plots

In [37]:
comp = pd.DataFrame({'AAPL': df['Close_AAPL'], 'MSFT': df['Close_MSFT']}).dropna()
comp

                  AAPL        MSFT
Date
2024-11-22  228.835022  414.721161
2024-11-25  231.821533  416.501373
2024-11-26  234.001663  425.651093
2024-11-27  233.872238  420.678436
2024-11-29  236.261444  421.145844
...                ...         ...
2025-11-10  269.429993  506.000000
2025-11-11  275.250000  508.679993
2025-11-12  273.470001  511.140015
2025-11-13  272.950012  503.290009
2025-11-14  272.410004  510.179993

[245 rows x 2 columns]

In [38]:
# Normalize (index=0 => 100%)
norm = comp / comp.iloc[0] * 100
norm

                  AAPL        MSFT
Date
2024-11-22  100.000000  100.000000
2024-11-25  101.305094  100.429255
2024-11-26  102.257802  102.635489
2024-11-27  102.201244  101.436453
2024-11-29  103.245317  101.549157
...                ...         ...
2025-11-10  117.739842  122.009689
2025-11-11  120.283162  122.655905
2025-11-12  119.505309  123.249080
2025-11-13  119.278076  121.356240
2025-11-14  119.042095  123.017594

[245 rows x 2 columns]

## pct = (xn / xn-1) - 1 in all elements
## first object wiil be NAN

In [45]:
# Daily returns and correlation
returns = comp.pct_change().dropna() # daily returns and dropna because first row will be NaN
corr = returns['AAPL'].corr(returns['MSFT'])

print('Correlation of daily returns (AAPL vs MSFT):', round(corr, 4))
print('\nTotal return (AAPL, MSFT):')
print(((comp.iloc[-1] / comp.iloc[0]) - 1).apply(lambda x: f"{x:.2%}"))

Correlation of daily returns (AAPL vs MSFT): 0.5128

Total return (AAPL, MSFT):
AAPL    19.04%
MSFT    23.02%
dtype: object

In [61]:
returns

                AAPL      MSFT
Date
2024-11-25  0.013051  0.004293
2024-11-26  0.009404  0.021968
2024-11-27 -0.000553 -0.011682
2024-11-29  0.010216  0.001111
2024-12-02  0.009523  0.017759
...              ...       ...
2025-11-10  0.004549  0.018478
2025-11-11  0.021601  0.005296
2025-11-12 -0.006467  0.004836
2025-11-13 -0.001901 -0.015358
2025-11-14 -0.001978  0.013690

[244 rows x 2 columns]

 ##  عدد أيام التداول في السنة عادةً 252 يوم

الصيغة التي استخدمتها: $\text{Annualized Return} = (\text{Total Return Factor})^{\frac{252}{\text{n\_days}}} - 1$

In [48]:

n_days = len(comp)
annualized_return = (comp.iloc[-1] / comp.iloc[0]) ** (252 / n_days) - 1
print('\nAnnualized return (approx):')
print(annualized_return.apply(lambda x: f"{x:.2%}"))

Annualized return (approx):
AAPL    19.64%
MSFT    23.75%
dtype: object

In [49]:
annualized_vol = returns.std() * (252 ** 0.5)
print('\nAnnualized vol (approx):')
print(annualized_vol.apply(lambda x: f"{x:.2%}"))

Annualized vol (approx):
AAPL    32.94%
MSFT    24.39%
dtype: object

In [27]:
# Plot normalized price
fig = px.line(norm, title='Normalized Price: AAPL vs MSFT (Base=100)')
fig.update_xaxes(rangeslider_visible=True)
fig.show()

In [52]:
df.columns

Index(['Close_AAPL', 'Close_AMZN', 'Close_GOOG', 'Close_META', 'Close_MSFT',
       'High_AAPL', 'High_AMZN', 'High_GOOG', 'High_META', 'High_MSFT',
       'Low_AAPL', 'Low_AMZN', 'Low_GOOG', 'Low_META', 'Low_MSFT', 'Open_AAPL',
       'Open_AMZN', 'Open_GOOG', 'Open_META', 'Open_MSFT', 'Volume_AAPL',
       'Volume_AMZN', 'Volume_GOOG', 'Volume_META', 'Volume_MSFT'],
      dtype='object')

In [51]:
# Scatter of daily returns with linear trendline
fig2 = px.scatter(returns, x='AAPL', y='MSFT', trendline='ols', title='Daily Returns: AAPL vs MSFT')
fig2.show()

In [30]:
# Candlesticks side-by-side (if you want raw prices)
fig3 = go.Figure()
fig3.add_trace(go.Scatter(x=comp.index, y=comp['AAPL'], name='AAPL Close'))
fig3.add_trace(go.Scatter(x=comp.index, y=comp['MSFT'], name='MSFT Close'))
fig3.update_layout(title='Close Price: AAPL vs MSFT', xaxis_rangeslider_visible=True)
fig3.show()

In [ ]:

# Add S&P 500 as a benchmark
benchmark_ticker = '^GSPC'
benchmark_df = yf.download(benchmark_ticker, 
                           start=start_date, 
                           end=end_date, 
                           progress=False)['Close']
benchmark_df.name = 'Close_GSPC'
print(benchmark_df.head())

C:\Users\Abdelruhman Elfekky\AppData\Local\Temp\ipykernel_7636\1664235571.py:4: FutureWarning:

YF.download() has changed argument auto_adjust default to True

Ticker            ^GSPC
Date
2024-11-22  5969.339844
2024-11-25  5987.370117
2024-11-26  6021.629883
2024-11-27  5998.740234
2024-11-29  6032.379883

In [54]:

# Merge the benchmark data with the existing comparison DataFrame
comp_full = pd.DataFrame({
    'AAPL': df['Close_AAPL'], 
    'MSFT': df['Close_MSFT'],
    'GOOG': df['Close_GOOG'],
    'AMZN': df['Close_AMZN'],
    'META': df['Close_META']
}).dropna() # Get the 5 stocks closing prices

# Add S&P 500 benchmark
comp_full['GSPC'] = benchmark_df

# Drop any rows where any stock or the benchmark is missing data
comp_full = comp_full.dropna()

print('*** Combined Data (Stocks + Benchmark) ***')
print(comp_full.tail())

*** Combined Data (Stocks + Benchmark) ***
                  AAPL        MSFT        GOOG        AMZN        META  \
Date
2025-11-10  269.429993  506.000000  290.589996  248.399994  631.760010
2025-11-11  275.250000  508.679993  291.739990  249.100006  627.080017
2025-11-12  273.470001  511.140015  287.429993  244.199997  609.010010
2025-11-13  272.950012  503.290009  279.119995  237.580002  609.890015
2025-11-14  272.410004  510.179993  276.980011  234.690002  609.460022

                   GSPC
Date
2025-11-10  6832.430176
2025-11-11  6846.609863
2025-11-12  6850.919922
2025-11-13  6737.490234
2025-11-14  6734.109863

3. تطبيع الأسعار (Normalization)للمقارنة العادلة، سنقوم بتطبيع أسعار جميع الأصول بحيث تبدأ جميعها من القيمة 100 في اليوم الأول.$$\text{Normalized Price} = \frac{\text{Current Price}}{\text{Starting Price}} \times 100$$

In [60]:
# Normalize all prices to 100 on the starting date
norm_full = (comp_full / comp_full.iloc[0]) * 100

print('*** Normalized Prices (Start at 100) ***')
print(norm_full.head())

*** Normalized Prices (Start at 100) ***
                  AAPL        MSFT        GOOG        AMZN        META  \
Date
2024-11-22  100.000000  100.000000  100.000000  100.000000  100.000000
2024-11-25  101.305094  100.429255  101.716975  102.196632  101.067712
2024-11-26  102.257802  102.635489  102.431399  105.448461  102.575383
2024-11-27  102.201244  101.436453  102.551468  104.372976  101.799187
2024-11-29  103.245317  101.549157  102.353349  105.463679  102.714889

                  GSPC
Date
2024-11-22  100.000000
2024-11-25  100.302048
2024-11-26  100.875977
2024-11-27  100.492523
2024-11-29  101.056064

In [64]:
norm_full

,AAPL,MSFT,GOOG,AMZN,META,GSPC
Date,,,,,,
2024-11-22,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
2024-11-25,101.305094,100.429255,101.716975,102.196632,101.067712,100.302048
2024-11-26,102.257802,102.635489,102.431399,105.448461,102.575383,100.875977
2024-11-27,102.201244,101.436453,102.551468,104.372976,101.799187,100.492523
2024-11-29,103.245317,101.549157,102.353349,105.463679,102.714889,101.056064
...,...,...,...,...,...,...
2025-11-10,117.739842,122.009689,175.218691,126.014610,113.343075,114.458723
2025-11-11,120.283162,122.655905,175.912109,126.369730,112.503445,114.696265
2025-11-12,119.505309,123.249080,173.313286,123.883930,109.261533,114.768469
2025-11-13,119.278076,121.356240,168.302560,120.525572,109.419414,112.868264
2025-11-14,119.042095,123.017594,167.012201,119.059460,109.342269,112.811635

In [67]:
# Plot normalized price comparison
fig_comp = px.line(norm_full, 
                   title='Normalized Performance: 5 Tech Stocks vs S&P 500 (GSPC)',
                   labels={'value': 'Normalized Price (Index 100)'})

fig_comp.update_xaxes(rangeslider_visible=True, title='Date')
fig_comp.update_yaxes(title='Normalized Price (Base 100)')
fig_comp.update_layout(legend_title_text='Asset')
fig_comp.show()

In [68]:
len(comp_full)

245

الصيغة التي استخدمتها: $\text{Annualized Return} = (\text{Total Return Factor})^{\frac{252}{\text{n\_days}}} - 1$

In [63]:
n_days_full = len(comp_full)

# Calculate Daily Returns
returns_full = comp_full.pct_change().dropna()

# 1. Annualized Return (CAGR)
annualized_return_full = (comp_full.iloc[-1] / comp_full.iloc[0]) ** (252 / n_days_full) - 1
print('*** Annualized Return (CAGR) ***')
print(annualized_return_full.apply(lambda x: f"{x:.2%}"))

*** Annualized Return (CAGR) ***
AAPL    19.64%
MSFT    23.75%
GOOG    69.48%
AMZN    19.65%
META     9.62%
GSPC    13.20%
dtype: object

In [62]:
# 2. Annualized Volatility
annualized_vol_full = returns_full.std() * (252 ** 0.5)
print('\n*** Annualized Volatility (Risk) ***')
print(annualized_vol_full.apply(lambda x: f"{x:.2%}"))

*** Annualized Volatility (Risk) ***
AAPL    32.94%
MSFT    24.39%
GOOG    32.23%
AMZN    35.04%
META    38.52%
GSPC    19.04%
dtype: object

الوزن (Weight) هو أهم عامل في تحليل المحفظة، وهو يمثل النسبة المئوية من إجمالي رأس المال المخصص لكل سهم داخل المحفظة.

الفائدة الجوهرية للوزن هي أنه يتحكم في العائد والمخاطر الإجمالية للمحفظة.

In [ ]:
# Define the weights for an equally weighted portfolio (5 assets)
weights = [0.20, 0.20, 0.20, 0.20, 0.20]  

# Confirm the sum of weights is 1 (100%)
print(f"Portfolio Weights: {weights}")
print(f"Sum of Weights: {sum(weights)}")

Portfolio Weights: [0.2, 0.2, 0.2, 0.2, 0.2]
Sum of Weights: 1.0

حساب العوائد اليومية للمحفظةسنقوم بحساب العائد اليومي للمحفظة باستخدام القانون:$$\text{Portfolio\_Returns} = \sum (\text{Stock\_Returns} \times \text{Weight})$$

In [70]:
# Calculate the daily returns for the 5 stocks (excluding the benchmark GSPC)
portfolio_returns_df = comp_full[['AAPL', 'MSFT', 'GOOG', 'AMZN', 'META']].pct_change().dropna()

# Calculate the daily portfolio return by multiplying stock returns by their weights and summing them up
portfolio_returns_series = (portfolio_returns_df * weights).sum(axis=1)
portfolio_returns_series.name = 'Portfolio_Returns'

print('*** Daily Portfolio Returns (Head) ***')
print(portfolio_returns_series.head())
print('\n*** Daily Portfolio Returns (Tail) ***')
print(portfolio_returns_series.tail())

*** Daily Portfolio Returns (Head) ***
Date
2024-11-25    0.013431
2024-11-26    0.017027
2024-11-27   -0.005766
2024-11-29    0.005768
2024-12-02    0.017536
Name: Portfolio_Returns, dtype: float64

*** Daily Portfolio Returns (Tail) ***
Date
2025-11-10    0.018890
2025-11-11    0.005253
2025-11-12   -0.012978
2025-11-13   -0.014367
2025-11-14   -0.001765
Name: Portfolio_Returns, dtype: float64

$$\text{الأداء التراكمي} = (1 + R_1) \times (1 + R_2) \times (1 + R_3) \times \dots \times (1 + R_n)$$

In [ ]:
n_days_port = len(portfolio_returns_series)

# 1. Annualized Portfolio Return (CAGR)
# To do this, we need the cumulative performance.
# We assume the portfolio starts at 1, and compound the daily returns.
portfolio_cumulative_performance = (1 + portfolio_returns_series).prod()

# Formula: (Cumulative Performance) ^ (252 / n_days) - 1
annualized_portfolio_return = (portfolio_cumulative_performance) ** (252 / n_days_port) - 1

# 2. Annualized Portfolio Volatility
annualized_portfolio_vol = portfolio_returns_series.std() * (252 ** 0.5)

print('*** Portfolio Annual Performance (Equally Weighted) ***')
print(f"Annualized Return (CAGR): {annualized_portfolio_return:.2%}")
print(f"Annualized Volatility: {annualized_portfolio_vol:.2%}")

*** Portfolio Annual Performance (Equally Weighted) ***
Annualized Return (CAGR): 29.57%
Annualized Volatility: 26.21%

In [72]:

# Calculate cumulative performance starting at 100
portfolio_normalized_performance = (1 + portfolio_returns_series).cumprod() * 100

# Combine the portfolio performance with the GSPC normalized performance
comparison_df = pd.DataFrame({
    'Equally_Weighted_Portfolio': portfolio_normalized_performance,
    'S&P_500 (GSPC)': norm_full['GSPC'].iloc[1:] # Use the normalized benchmark data
}).dropna()

# Plot the comparison
fig_portfolio = px.line(comparison_df, 
                        title='Portfolio Performance vs S&P 500 Benchmark',
                        labels={'value': 'Normalized Price (Index 100)', 'Date': 'Date'})

fig_portfolio.update_xaxes(rangeslider_visible=True)
fig_portfolio.show()